DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

mysite/urls.py
from django.conf.urls import url
from . import views

# app_name = 'mysite'     # 可以 <a href="{% url 'mysite:index' %}">，以区别不同app下的同一个命空间
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^news-index/$', views.news_index, name='news-index'),
    url(r'^news-index/(?P<pk>\d+)/', views.news_detail, name='news-detail'),
    url(r'^blog-index/$', views.blog_index, name='blog-index'),
    url(r'^blog-index/(?P<pk>\d+)/', views.blog_detail, name='blog-detail'),
    url(r'^share-index/', views.share_index, name='share-index'),
    url(r'^tag/(?P<tag>\S+)/', views.tag, name='tag'),
    url(r'^ajax_feedback/', views.ajax_feedback, name='ajax_feedback'),
]

myxing/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from DjangoUeditor import urls as DjangoUeditor_urls
from django.conf.urls.static import static, settings

urlpatterns = [
    url(r'', include('mysite.urls')),
    url(r'', include('user_admin.urls')),
    url(r'^ueditor/', include(DjangoUeditor_urls)),
    url(r'^admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib import admin
from django.urls import reverse
from DjangoUeditor.models import UEditorField
from user_admin.models import Reg_user
import re


# 热门网址-------------------------------------------------------------------
class Top_url(models.Model):
    name = models.CharField('名称', max_length=15)
    url = models.URLField('网址')
    logo = models.FileField('LOGO', upload_to='url_logo')
    rank = models.IntegerField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'B1_热门网址'
        ordering = ['rank']


class Top_url_admin(admin.ModelAdmin):
    list_display = ('name', 'url', 'logo', 'rank')


admin.site.register(Top_url, Top_url_admin)


# 分类网址标签、分类网址-----------------------------------------------------
class Sort_tag(models.Model):
    name = models.CharField(max_length=10)
    rank = models.IntegerField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'B2_分类标签'
        ordering = ['rank']


class Sort_url(models.Model):
    sort = models.ForeignKey(Sort_tag,on_delete=models.CASCADE)
    name = models.CharField(max_length=15)
    url = models.URLField()
    logo = models.FileField(upload_to='url_logo', blank=True)
    rank = models.IntegerField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'B3_分类网址'
        ordering = ['sort', 'rank']


class Sort_tag_admin(admin.ModelAdmin):
    list_display = ('name', 'rank')


admin.site.register(Sort_tag, Sort_tag_admin)


class Sort_url_admin(admin.ModelAdmin):
    list_display = ('sort', 'name', 'url', 'logo', 'rank')


admin.site.register(Sort_url, Sort_url_admin)


# 新闻标签--------------------------------------------------------------------
class News_tag(models.Model):
    name = models.CharField(max_length=10)
    rank = models.IntegerField(default=99)

    def __str__(self):
        return self.name
        ordering = ['rank']

    def get_tag_url(self):
        return reverse('tag', args=(self.name, ))

    class Meta:
        verbose_name_plural = 'C1_新闻标签'


class News_tag_admin(admin.ModelAdmin):
    list_display = ('name', 'rank')


admin.site.register(News_tag, News_tag_admin)


# 新闻来源-------------------------------------------------------------------------
class Origin(models.Model):
    name = models.CharField(max_length=10)
    url = models.URLField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'C2_新闻来源'


class Origin_admin(admin.ModelAdmin):
    list_display = ('name', 'url')


admin.site.register(Origin, Origin_admin)


# 新闻内容-------------------------------------------------------------------------
class News(models.Model):
    IS_TOP_CHOICES = (
        ('Y', 'yes'),
        ('N', 'no'),
    )
    title = models.CharField(max_length=50)
    IS_TOP = models.CharField(
        max_length=5, choices=IS_TOP_CHOICES, default='N')
    news_tag = models.ManyToManyField(News_tag)
    origin = models.ForeignKey(Origin,on_delete=models.CASCADE)
    main_img = models.ImageField(upload_to='news_main_img', blank=True)
    published_date = models.DateTimeField(auto_now_add=True)
    # published_date2 = models.CharField(default = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()),max_length = 50)
    content = UEditorField('内容', height=300, width=1000, default=u'', blank=True,
                           imagePath='news_img/', toolbars='besttome', filePath='news_files/')

    def __str__(self):
        return self.title

    # 得到文章摘要，此方法效率低。可以用更好的方法来实现，如重写save()方法，或直接创建一个关于摘要的字段。
    def get_news_abstract(self):
        # 匹配html tag 及其中的内容，如<div class='box'>。<不含 > 的字符，1次或多次>
        RE_ABSTRACT = r'<[^>]+>'
        # compile regular expression patten into a regular expression object
        pattern = re.compile(RE_ABSTRACT)
        # print(pattern.sub('',self.content[0:300]))
        return pattern.sub('', self.content[0:500])  # 用空内容取消html标签及其中的内容

    def get_news_url(self):
        return reverse('news-detail', args=(self.pk,))

    class Meta:
        verbose_name_plural = 'C3_新闻内容'
        ordering = ['-published_date']


class News_admin(admin.ModelAdmin):
    list_display = ('title', 'origin', 'published_date', 'IS_TOP')


admin.site.register(News, News_admin)


# 新闻评论----------------------------------------------------------------------------
class News_comment(models.Model):
    news_title = models.ForeignKey(News,on_delete=models.CASCADE)
    comment = models.ForeignKey(Reg_user,on_delete=models.CASCADE)
    comment_time = models.DateTimeField(auto_now_add=True)
    comment_text = models.TextField(blank=True)

    def __str__(self):
        return self.comment_text

    class Meta:
        verbose_name_plural = ('C4_新闻评论')
        ordering = ['-comment_time']


class News_comment_admin(admin.ModelAdmin):
    list_display = ('news_title', 'comment_time', 'comment_text')


admin.site.register(News_comment, News_comment_admin)


# 博客标签----------------------------------------------------------------------------
class Blog_tag(models.Model):
    name = models.CharField(max_length=10)
    tag_img = models.FileField(upload_to='tag_img', blank=True)
    rank = models.IntegerField(default=99)

    def __str__(self):
        return self.name
        ordering = ['rank']

    def get_tag_url(self):
        return reverse('tag', args=[self.name])

    class Meta:
        verbose_name_plural = 'D1_博客标签'


class Blog_tag_admin(admin.ModelAdmin):
    list_display = ('name', 'tag_img', 'rank')


admin.site.register(Blog_tag, Blog_tag_admin)


# 博客内容-----------------------------------------------------------------------------
class Blog(models.Model):
    IS_TOP_CHOICES = (
        ('Y', 'yes'),
        ('N', 'no'),
    )
    IS_TOP = models.CharField(
        max_length=5, choices=IS_TOP_CHOICES, default='N')
    title = models.CharField(max_length=100)
    blog_author = models.ForeignKey(Reg_user,on_delete=models.CASCADE)
    blog_tag = models.ManyToManyField(Blog_tag, blank=True)
    published_date = models.DateTimeField(auto_now_add=True)
    main_img = models.ImageField(upload_to='blog_main_img', blank=True)
    content = UEditorField('内容', height=300, width=1000, default=u'', blank=True,
                           imagePath='blog_content_img/', toolbars='besttome', filePath='blog_files/')
    blog_click = models.IntegerField(default=0)
    blog_love = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'D2_博客内容'
        ordering = ['-IS_TOP', '-published_date']

    def get_blog_abstract(self):
        RE_ABSTRACT = r'<[^>]+>'
        pattern = re.compile(RE_ABSTRACT)
        return pattern.sub('', self.content[0:300])

    def get_blog_url(self):
        return reverse('blog-detail', args=(self.pk,))


class Blog_admin(admin.ModelAdmin):
    list_display = ('title', 'blog_author', 'IS_TOP', 'published_date')


admin.site.register(Blog, Blog_admin)


# 博客评论----------------------------------------------------------------------------
class Blog_comment(models.Model):
    blog_title = models.ForeignKey(Blog, on_delete=models.CASCADE)
    comment = models.ForeignKey(Reg_user, on_delete=models.CASCADE)
    comment_time = models.DateTimeField(auto_now_add=True)
    comment_text = models.TextField(blank=True)

    def __str__(self):
        return self.comment_text

    class Meta:
        verbose_name_plural = ('D3_博客评论')
        ordering = ['-comment_time']


class Blog_comment_admin(admin.ModelAdmin):
    list_display = ('blog_title', 'comment_time', 'comment_text')


admin.site.register(Blog_comment, Blog_comment_admin)


# 分享标签------------------------------------------------------------------------
class Share_tag(models.Model):
    tag_name = models.CharField(max_length=10)
    rank = models.ImageField(default=99)

    def __str__(self):
        return self.tag_name

    class Meta:
        verbose_name_plural = ('E1_分享标签')
        ordering = ['-rank']


class Share_tag_admin(admin.ModelAdmin):
    list_display = ('tag_name', 'rank')


admin.site.register(Share_tag, Share_tag_admin)


# 分享文件-------------------------------------------------------------------------
class Share_file(models.Model):
    share = models.ForeignKey('Share',on_delete = models.CASCADE)
    share_file = models.FileField(upload_to='share_file', blank=True)

    class Meta:
        verbose_name_plural = ('E2_分享文件')

    def get_file_name(self):
        return self.share_file.name.split('/')[-1]


class Share_file_admin(admin.ModelAdmin):
    list_display = ('share', 'share_file',)


admin.site.register(Share_file, Share_file_admin)


# 分享----------------------------------------------------------------------------
class Share(models.Model):
    author = models.ForeignKey(Reg_user,on_delete = models.CASCADE)
    share_title = models.CharField(max_length=20, blank=True)
    share_time = models.DateTimeField(auto_now_add=True)
    share_desc = models.TextField(blank=True)
    share_tag = models.ManyToManyField(Share_tag)

    def __str__(self):
        return self.share_title

    def show_tag(self):
        return ",".join([t.tag_name for t in self.share_tag.all()])
    show_tag.short_description = 'tag'

    class Meta:
        verbose_name_plural = ('E3_分享')


class Share_admin(admin.ModelAdmin):
    list_display = ('author', 'share_title', 'share_time',
                    'share_desc', 'show_tag')


admin.site.register(Share, Share_admin)


# 反馈----------------------------------------------------------------------------
class Feedback(models.Model):
    feedback_content = models.CharField(max_length=300)
    feedback_contact = models.CharField(max_length=100, blank=True)
    feedback_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.feedback_content

    class Meta:
        verbose_name_plural = ('F1_反馈')

mysite/forms.py
# -*- coding: utf-8 -*-

from django import forms

class CommentForm(forms.Form):
    '''
    评论表单
    '''
    comment_text = forms.CharField(max_length=200,
                                   widget=forms.Textarea(attrs={
                                       'class': 'comment-text',
                                       'placeholder': '请登录后评论,最多200字',
                                   }))

mysite/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, redirect
from django.http import HttpResponse
from . models import *
from .forms import CommentForm
from django.db.models import Count
from django.core.mail import send_mail
from django.contrib.auth.hashers import make_password, check_password
from django.views.decorators.csrf import csrf_exempt
from common_functions.my_paginator import common_paginator

# 主页


def index(request):
    top_url = Top_url.objects.all()
    sort_tag = Sort_tag.objects.all()
    blog_hot = Blog.objects.filter(IS_TOP='Y')
    news_tag_list = News_tag.objects.annotate(
        arcticle_num=Count('news')).order_by('-arcticle_num')[:12]
    blog_tag_list = Blog_tag.objects.annotate(
        arcticle_num=Count('blog')).order_by('-arcticle_num')[:12]
    news = News.objects.annotate(comment_num=Count(
        'news_comment')).order_by('-comment_num')[:4]
    blog = Blog.objects.annotate(comment_num=Count(
        'blog_comment')).order_by('-comment_num')[:6]
    share = Share.objects.all()[:4]
    return render(request, 'mysite/index.html', locals())


# 新闻主页
def news_index(request):
    comment_num = News.objects.annotate(comment_num=Count(
        'news_comment')).order_by('-comment_num')[:5]
    news_tag = News_tag.objects.all()

    news_list = News.objects.all()
    news = common_paginator(request, news_list, 5)
    return render(request, 'mysite/news-index.html', locals())


# 新闻详情页
def news_detail(request, pk):
    session_username = request.session.get('session_username')
    now_url = request.path
    news = News.objects.get(pk=pk)
    news_tag_list = News_tag.objects.filter(news__pk=pk)
    if request.method == 'POST':
        cf = CommentForm(request.POST)
        if cf.is_valid():
            author = Reg_user.objects.get(username=session_username)
            add_comment = News_comment.objects.create(news_title=news, comment=author,
                                                      comment_text=cf.cleaned_data['comment_text'])
            response = redirect(now_url + '#newsdetail-comment')
            return response
    else:
        cf = CommentForm()

    return render(request, 'mysite/news-detail.html', locals())


# 博客主页
def blog_index(request):
    blog_tag = Blog_tag.objects.all()
    comment_num = Blog.objects.annotate(comment_num=Count(
        'blog_comment')).order_by('-comment_num')[:5]
    blog_num = Reg_user.objects.annotate(
        blog_num=Count('blog')).order_by('-blog_num')[:5]
    blog_list = Blog.objects.filter(IS_TOP='N')
    blog = common_paginator(request, blog_list, 5)
    return render(request, 'mysite/blog-index.html', locals())


# 博客详情页
def blog_detail(request, pk):
    session_username = request.session.get('session_username') 
    now_url = request.path
    blog = Blog.objects.get(pk=pk)
    if request.method == 'POST':
        author = Reg_user.objects.get(username=session_username)
        cf = CommentForm(request.POST)
        if cf.is_valid():
            blog_title = Blog.objects.get(pk=pk)
            add_comment = Blog_comment.objects.create(blog_title=blog_title, comment=author,
                                                      comment_text=cf.cleaned_data['comment_text'])
            response = redirect(now_url + '#blogdetail-comment')
            return response
    else:
        cf = CommentForm()
    return render(request, 'mysite/blog-detail.html', locals())


# 标签页
def tag(request, tag):
    try:
        news_tag = News_tag.objects.get(name=tag)
    except:
        try:
            blog_tag = Blog_tag.objects.get(name=tag)
        except:
            author_tag = Reg_user.objects.get(username=tag)

    if request.method == 'POST':
        author = Reg_user.objects.get(username=username)
        cf = CommentForm(request.POST)
        if cf.is_valid():
            blog_title = Blog.objects.get(pk=pk)
            add_comment = Blog_comment.objects.create(blog_title=blog_title, comment=author,
                                                      comment_text=cf.cleaned_data['comment_text'])
            response = redirect(now_url + '#blogdetail-comment')
            return response
    else:
        cf = CommentForm()
    return render(request, 'mysite/tag.html', locals())


# 分享页
def share_index(request):
    share_list = Share.objects.all()
    return render(request, 'mysite/share-index.html', locals())


# ajax，反馈功能，发邮件
@csrf_exempt
def ajax_feedback(request):
    # print(request.POST)
    feedback_content = request.POST['feedback_content']
    feedback_contact = request.POST['feedback_contact']
    # print(feedback_content)
    # print(feedback_contact)
    if feedback_content:
        feedback = Feedback.objects.create(
            feedback_content=feedback_content, feedback_contact=feedback_contact)
        send_mail(
            'blog-反馈信息',
            feedback_contact+'\n'+feedback_content,
            'admin@xxx.com',
            ['xxx@qq.com'],
            fail_silently=False
        )
    else:
        return HttpResponse(False)
    return HttpResponse(True)

mysite/templates/mysite/index.html
{% extends 'base.html' %} 
{% load static %}
{% block title %}首页{% endblock %} {% block tag %}
<base target="_blank">{% endblock %} 
{% block css%}<link rel="stylesheet" href="{% static 'mysite/css/index.css' %}">{% endblock %}
{% block js %}<script type="text/javascript" src="{% static 'mysite/javascript/index.js' %}"></script>{% endblock %}
{% block content %}
<div class="body-box fixed-margin-top">
    <div class="body-top clearfix">
        <div class="body-nav">
            <div class="nav-hot">
                <ul class="hot-url-list">
                    {% for top_url in top_url %}
                    <li class="hot-url-info"><a href="{{ top_url.url }}" title="{{ top_url.name }}" style="background-image:url({{ top_url.logo.url }})">{{ top_url.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>

            <div class="nav-category">
                {% for sort_tag in sort_tag %}
                <div class="category-box">
                    <span class="category-tag">{{ sort_tag }}</span>
                    <ul class="category-url-list">
                        {% for sort_url in sort_tag.sort_url_set.all|slice:":6" %}
                        <li class="category-url-info"><a href="{{ sort_url.url }}" style="background-image:">{{ sort_url.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="body-side">
            <div class="ppt" id="ppt">
                <ul class="ppt-num" id="ppt-num">
                    <li class="num active">•</li>
                    <li class="num">•</li>
                    <li class="num">•</li>
                    <li class="num">•</li>
                </ul>
                <ul class="ppt-img" id="ppt-img">
                    {% for blog_hot in blog_hot %}
                    <li class="img"><a href="{{ blog_hot.get_blog_url }}"><img src="{{ blog_hot.main_img.url }}" alt="图片"></a></li>
                    {% endfor %}
                </ul>
            </div>
            <div>
                <ul class="hot-blog-list">
                    {% for blog_hot in blog_hot %}
                    <li class="hot-blog"><a href="{{ blog_hot.get_blog_url }}" title="{{ blog_hot.title }}">{{ blog_hot.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="tag-list">
                <div class="news-tag-list">
                    <span class="tag-title">资讯标签</span> {% for news_tag in news_tag_list %}
                    <a class="hot-news-tag" href="{{ news_tag.get_tag_url }}">{{ news_tag.name }}</a> {% endfor %}
                </div>
                <div class="blog-tag-list">
                    <span class="tag-title">博客标签</span> {% for blog_tag in blog_tag_list %}
                    <a class="hot-blog-tag" href="{{ blog_tag.get_tag_url }}">{{ blog_tag.name }}</a> {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="body-bottom clearfix">
        <div class="news-blog">
            <div class="news-list">
                <div class="colum"><a href="{% url 'news-index' %}">资讯头条</a></div>
                {% for news in news %}
                <div class="news clearfix">
                    <a href="{{ news.get_news_url }}" class="news-img"><img src="{{ news.main_img.url}}" alt="图片"></a>
                    <div class="news-info">
                        <a href="{{ news.get_news_url }}" title="{{ news.title }}">
                            <h4 class="news-title">{{ news.title }}</h4>
                        </a>
                        <div class="news-sub">{#{{ news.get_news_abstract }}#}</div>
                        <div class="news-attach1">
                            {% for news_tag in news.news_tag.all %}
                            <div class="news-tag"><a href="{{ news_tag.get_tag_url }}">{{ news_tag.name }}</a></div>
                            {% endfor %}
                        </div>
                        <div class="news-attach2">
                            <div class="published-time">{{ news.published_date |date:"n月j日 G:i"}}</div>
                            <div class="comment-share"><a href="{{ news.get_news_url }}#newsdetail-comment">评论（{{ news.news_comment_set.all.count }}）</a></div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

            <div class="blog-list">
                <div class="colum"><a href="{% url 'blog-index' %}">博客排行</a></div>
                {% for blog in blog %}
                <div class="blog-info">
                    {% if blog.main_img %}
                    <div class="blog-info-img"><img src="{{ blog.main_img.url }}" alt=""></div>
                    {% endif %}
                    <div class="blog-title-abstract">
                        <div class="blog-title-time">
                            <a href="{{ blog.get_blog_url }}" class="blog-title">{{ blog.title }}</a>
                            <span class="blog-time">{{ blog.published_date|date:"n月j日 G:i" }}</span>
                        </div>
                        <div class="blog-abstract">{{ blog.get_blog_abstract }}</div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="share-list">
            <div class="colum"><a href="{% url 'share-index' %}">热门分享</a></div>
            {% for share in share %}
            <div class="share-info">
                <div class="share-author-title">
                    <div class="author-img"><img src="{{share.author.user_img.url }}"></div>
                    <div class="author-name">{{ share.author.username }}</div>
                    <div class="share-title"><a href="{% url 'share-index' %}#{{share.share_title}}">{{ share.share_title }}</a></div>
                </div>
                <div class="share-desc">{{ share.share_desc }}</div>
                {% for share_file in share.share_file_set.all %}
                <div class="share-file"><a href="{% url 'share-index' %}#{{share.share_title}}">{{ share_file.get_file_name }}</a></div>
                {% endfor %}
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mysite/templates/mysite/news-detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ news.title }}{% endblock %}
{% block css %}<link rel="stylesheet" href="{% static 'mysite/css/news-detail.css' %}">{% endblock %}
{% block content %}

<div class="newsdetail-box clearfix">
	<div class="newsdetail-news ">
    	<div class="newsdetail-content">
        	<div class="newsdetail-top">
            	<h2 class="newsdetail-title">{{ news.title }}</h2>
                <div class="newsdetail-attach">
                	<div class="newsdetail-from"><a href="{{ news.origin.url }}">{{ news.origin }}</a></div>
                    {% for news_tag in news.news_tag.all %} 
                    <div class="newsdetail-tag"><a href="{{ news_tag.get_tag_url }}">{{ news_tag }}</a></div>
                    {% endfor %}
                    <div class="newsdetail-time">{{ news.published_date|date:"n月j日 G:i" }}</div>
                    <div class="newsdetail-comment-top"><a href="#newsdetail-comment">评论({{news.news_comment_set.all.count}})</a></div>
                </div>
            </div>
            <div class="newsdetail-body">
            {{ news.content | safe }}
            </div>
        </div>
        <div class="newsdetail-comment" id="newsdetail-comment">
            <form method="post">
                {% for field in cf %}
                {% csrf_token %}
                <div>{{field}}</div>
                {% endfor %}
            
                <div class="log-submit">
                    <span class="comment_num">{{ news.news_comment_set.all.count }}条评论</span>
                    {% if session_username %}
                        <span class="username_form"><a href="{% url 'useradmin' %}">{{session_username}}</a></span>
                        <input type="submit" class="submit_btn" value="提交">
                    {% else %}
                        <span class="log_btn"><a href="{% url 'login' %}">登录</a></span>
                    {% endif %}
                </div>
            </form>
            <div class="comment-list">
            	{% for comment in news.news_comment_set.all %}
            	<div class="comment-box clearfix">
                	<a href="#" class="comment-img"><img src="{{comment.comment.get_img_url}}" alt=""></a>
					<div class="comment-detail">                
                        <div class="comment-name-time"><span class="username">{{ comment.comment }}</span><span class="time">{{ comment.comment_time|date:"n月j日 G:i" }}</span></div>
                        <div class="comment-word">{{ comment.comment_text }}</div>

                	</div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="newsdetail-relative">
    	<div class="relative-news">相关新闻</div>
        <div class="relative-list">
            {% for news_tag in news_tag_list %}
        	<ul>
                {% for each_news in news_tag.news_set.all %}
                {% if each_news.pk != news.pk %}
            	<li><a href="{{each_news.get_news_url }}">{{ each_news.title }}</a></li>
                {% endif %}
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mysite/templates/mysite/share-index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}分享{% endblock %}
{% block css%}<link rel="stylesheet" href="{% static 'mysite/css/share-index.css' %}">{% endblock %}
{% block content %}
<div class="share-box">
	<div class="share-name">分享</div>
    <div class="share-list">
    	{% for share in share_list %}
    	<div class="share-info clearfix">
        	<div class="author-info">
            	<div class="author-img"><a href="{{ share.author.get_author_url }}"><img src="{{ share.author.user_img.url }}"></a></div>
                <div class="author-name">{{ share.author.username }}</div>
                <div class="share-num">{{ share.author.share_set.all.count }}次分享</div>
                <!-- <div class="file-num">{#{}#}个文件</div> -->
            </div>
            <div class="file-info">
        		<div class="share-title-tag">
                    <h4 class="share-title" id="{{ share.share_title }}">{{ share.share_title }}</h4>
                    {% for share_tag in share.share_tag.all %}
                    <span class="share-tag">{{ share_tag.tag_name }}</span>
                    {% endfor %}
                </div>  
                <div class="share-desc">{{ share.share_desc }}</div>
                {% for share_file in share.share_file_set.all %}
                <div class="share-file"><span>附件{{forloop.counter}}:</span><a class="share_url "href="{{ share_file.share_file.url }}">{{ share_file.get_file_name }}</a></div>
                {% endfor %}
        	</div>
    	</div>
        {% endfor %}
	</div>
</div>
{% endblock %}